services: 
  orders:
    build: .
    command: go run main.go
    env_file:
      - .env
    networks:
      - kafka-network
    volumes:
      - .:/orders

  kafka: 
    image: apache/kafka:latest
    networks:
      - kafka-network
    environment:
      # https://hub.docker.com/r/apache/kafka
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

networks:
  kafka-network:
    driver: bridge