services: 
  orders:
    build: .
    command: go run main.go
    env_file:
      - .env
    networks:
      - kafka-network
      - postgres-network
    volumes:
      - .:/orders

  kafka: 
    # https://hub.docker.com/r/apache/kafka
    image: apache/kafka:latest
    networks:
      - kafka-network
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

  postgres:
    # https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/
    image: postgres:alpine
    networks:
      - postgres-network
    volumes:
      - pgdata:/var/lib/postgresql/data 
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

networks:
  kafka-network:
    driver: bridge
  postgres-network:
    driver: bridge

volumes:
  pgdata: